# -*- coding: utf-8 -*-
"""SparkAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xPTw9wCYXJ2eMRne7F1Xo8LjALswTrir

SparkAI: Predicting Electric Vehicle (EV) Range and Building a Generative AI Chatbot

This project addresses range anxiety experienced by electric vehicle (EV) users by developing an AI-driven system to accurately predict driving range. The model uses real-world factors including vehicle parameters, trip data, and environmental conditions for improved accuracy. Additionally, a generative AI-powered chatbot will provide users with clear, interactive explanations and tips about their vehicle’s performance and predicted range.

**STEP 1:** the focus is on building a robust machine learning model to predict the remaining driving range of electric vehicles (EVs). This involves data cleaning, feature engineering, and training an XGBoost regression model tuned for accuracy using real-world factors like vehicle specs, trip conditions, and environment data. The model is evaluated, interpreted via feature importance, and saved for deployment. This foundational step sets the stage for integrating with user-facing components in subsequent phases.

# File Upload Process
"""

from google.colab import files
uploaded = files.upload()



"""# Data Cleaning and Feature Engineering Process"""

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

df1 = pd.read_csv("ChargingBundles.csv")
df2 = pd.read_csv("SyntheticTripsCanaryWharf.csv")
df3 = pd.read_csv("SyntheticTripsWestfield.csv")

df_combined = pd.concat([df1, df2, df3], ignore_index=True)

numeric_features = [
    "Charging_Rate",
    "Charging_FirstHour",
    "Charging_SecondHour",
    "Charging_ThirdHour",
    "Charging_FourthHour",
    "Parking",
    "Dummy_Age",
    "WalkingDistance_Parking1",
    "WalkingDistance_Parking2"
]
target_column = "Energy_Required"

X = df_combined[numeric_features]
y = df_combined[target_column]


X = X.fillna(0)
y = y.fillna(y.mean())


X = df_combined[numeric_features]
y = df_combined[target_column]
X = X.fillna(0)
y = y.fillna(y.mean())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

numeric_model = xgb.XGBRegressor(n_estimators=500, learning_rate=0.05)
numeric_model.fit(X_train, y_train)
numeric_model.save_model("ev_range_numeric_model.json")

import pandas as pd

data = {
    "VehicleWeight": [1500, 1600],
    "Battery_kWh": [60, 75],
    "Motor_kW": [100, 120],
    "Avg_Speed": [50, 60],
    "Ambient_Temp": [25, 20],
    "Trip_km": [100, 150]
}

df = pd.DataFrame(data)
df.to_csv("ev_range_model", index=False)

df1.to_csv('ChargingBundles_modified.csv', index=False)
df2.to_csv('SyntheticTripsCanaryWharf_modified.csv', index=False)
df3.to_csv('SyntheticTripsWestfield_modified.csv', index=False)

import pandas as pd

df_combined = pd.concat([df1, df2, df3], ignore_index=True)
df_combined.to_csv("EVs_One_Combined.csv", index=False)

feature_columns = [
    'Charging_Rate', 'Charging_FirstHour', 'Charging_SecondHour',
    'Charging_ThirdHour', 'Charging_FourthHour', 'Parking', 'Dummy_Age',
    'Dummy_Gender', 'Dummy_EmploymentStatus', 'Dummy_MaritalStatus',
    'Dummy_Children', 'Dummy_Income', 'WalkingDistance_Parking1',
    'WalkingDistance_Parking2', 'ParkingLocation', 'Dummy_WorkBasedTour', 'Weekday'
]
target_column = 'Energy_Required'

print(df_combined['Energy_Required'].isna().sum())
df_combined = df_combined.dropna(subset=['Energy_Required'])
df_combined['Energy_Required'] = df_combined['Energy_Required'].fillna(df_combined['Energy_Required'].mean())
print(X_train.isna().sum())

model = xgb.XGBRegressor(n_estimators=500, learning_rate=0.05)
model.fit(X_train, y_train)

import xgboost as xgb

model = xgb.XGBRegressor(n_estimators=500, learning_rate=0.05)
model.fit(X_train, y_train)

model.save_model("ev_range_model.json")

"""# Tuned XGBoost hyperparameters using RandomizedSearchCV with early stopping and evaluated using RMSE.

"""

import numpy as np
import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from sklearn.metrics import mean_squared_error

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = xgb.XGBRegressor(n_estimators=10000, early_stopping_rounds=20, n_jobs=-1, random_state=42)

param_distributions = {
    "learning_rate": np.linspace(0.01, 0.2, 20),
    "subsample": np.linspace(0.5, 1.0, 6),
    "colsample_bytree": np.linspace(0.5, 1.0, 6),
    "min_child_weight": [1, 3, 5, 7],
    "max_depth": list(range(3, 16)),
    "alpha": [0, 0.01, 1, 5, 10],
    "lambda": [0, 0.01, 1, 5, 10]
}

random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_distributions,
    n_iter=40,
    scoring='neg_mean_squared_error',
    cv=3,
    verbose=1,
    n_jobs=-1,
    random_state=42
)

random_search.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=False
)

best_model = random_search.best_estimator_

print("Best hyperparameters:", random_search.best_params_)

y_pred = best_model.predict(X_val)
rmse = np.sqrt(mean_squared_error(y_val, y_pred))
print("Validation RMSE:", rmse)

"""# Performed a two-step train-test split for model training and evaluation.

"""

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print("Train set size:", X_train.shape[0])
print("Validation set size:", X_val.shape[0])
print("Test set size:", X_test.shape[0])

"""# Trained an XGBoost regressor with early stopping on validation data and evaluated performance using RMSE and MAE metrics.

"""

import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error

df = pd.read_csv('ChargingBundles_modified.csv')

if 'Parking' in df.columns:
    df['Parking'] = df['Parking'].astype('category')

X = df.drop('Charging_Rate', axis=1)
y = df['Charging_Rate']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

model = xgb.XGBRegressor(
    objective='reg:squarederror',
    eval_metric='rmse',
    learning_rate=0.02,
    max_depth=14,
    n_estimators=1000,
    subsample=1.0,
    min_child_weight=7,
    colsample_bytree=0.9,
    reg_lambda=10,
    reg_alpha=10,
    early_stopping_rounds=20,
    enable_categorical=True,
    random_state=42
)

model.fit(
    X_train,
    y_train,
    eval_set=[(X_val, y_val)],
    verbose=True
)

print("Best iteration:", model.best_iteration)
y_pred = model.predict(X_val, iteration_range=(0, model.best_iteration))
rmse = np.sqrt(mean_squared_error(y_val, y_pred))
mae = mean_absolute_error(y_val, y_pred)

print(f"Validation RMSE: {rmse}")
print(f"Validation MAE: {mae}")

"""# Saved the trained model"""

model.save_model('ev_range_model.json')
import xgboost as xgb

loaded_model = xgb.XGBRegressor()
loaded_model.load_model('ev_range_model.json')

from openai import OpenAI

OPENAI_API_KEY = "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"

client = OpenAI(api_key=OPENAI_API_KEY)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import xgboost as xgb
# import numpy as np
# from openai import OpenAI
# NUMERIC_MODEL_FILE = "ev_range_model.json"
# numeric_model = xgb.XGBRegressor()
# numeric_model.load_model(NUMERIC_MODEL_FILE)
# OPENAI_API_KEY = "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"  # Replace with your actual key
# client = OpenAI(api_key=OPENAI_API_KEY)
# 
# st.title("⚡ SparkAI – EV Range Predictor & Smart Chatbot")
# st.write("Predict EV range, ask questions, or get driving tips.")
# 
# st.subheader("💬 SparkAI Chatbot")
# 
# if "messages" not in st.session_state:
#     st.session_state["messages"] = []
# 
# user_input = st.text_input("Ask SparkAI anything about EV range:")
# 
# if user_input:
#     st.session_state.messages.append({"role": "user", "content": user_input})
# 
#     prompt = f"""
#     You are SparkAI, an EV assistant.Answer the user's question clearly and concisely in 1-2 sentences.
#     Topics: EV range, battery efficiency, trip planning, charging tips, and driving tips.
#     User question: {user_input}
#     """
# 
# 
#     try:
#         response = client.chat.completions.create(
#             model="gpt-4o-mini",
#             messages=[{"role": "user", "content": prompt}]
#         )
#         reply = response.choices[0].message.content
#     except Exception as e:
#         reply = f"⚠ Chatbot error: {e}"
# 
#     st.session_state.messages.append({"role": "assistant", "content": reply})
# 
# for msg in st.session_state.messages:
#     if msg['role'] == 'user':
#         st.markdown(f"**🧑 You:** {msg['content']}")
#     else:
#         st.markdown(f"**🤖 SparkAI:** {msg['content']}")
# 
# st.subheader("🔋 Predict EV Range")
# 
# with st.form("prediction_form"):
#     col1, col2 = st.columns(2)
#     with col1:
#         vehicle_weight = st.number_input("Vehicle Weight (kg)")
#         battery_capacity = st.number_input("Battery Capacity (kWh)")
#         motor_power = st.number_input("Motor Power (kW)")
#     with col2:
#         avg_speed = st.number_input("Average Speed (km/h)")
#         ambient_temp = st.number_input("Ambient Temperature (°C)")
#         trip_distance = st.number_input("Trip Distance (km)")
#     submitted = st.form_submit_button("Predict Range")
# 
# if submitted:
# 
#     features = np.array([[vehicle_weight, battery_capacity, motor_power,
#                           avg_speed, ambient_temp, trip_distance]])
#     try:
#         prediction = numeric_model.predict(features)[0]
#         st.success(f"🔮 Estimated Remaining Range: **{prediction:.2f} km**")
#         st.info("Tip: Ask the chatbot for driving efficiency tips!")
#     except Exception as e:
#         st.error(f"⚠ Prediction error: {e}")
#

!pip install pyngrok

from pyngrok import ngrok

NGROK_AUTH_TOKEN = "35Sb8zkIzalwrW7BPIeAjpwwYiM_7qonP1Z7Ns6cPpBf11zJC"

!ngrok config add-authtoken $NGROK_AUTH_TOKEN

print("Ngrok authentication successful!")

!streamlit run app.py &>/content/logs.txt &

!pgrep -af streamlit

!tail -n 50 /content/logs.txt

!pip install streamlit pyngrok xgboost pandas numpy openai --quiet

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &>/content/logs.txt &

!pkill ngrok

from pyngrok import ngrok
public_url = ngrok.connect(8501)
public_url

